package Others.java;

import java.util.Timer;
import java.util.TimerTask;



public class Teste {
	
	public static String tratamentoSqlInjectEmString(String dados) {
		  if(dados != null) {
		    String[] dangerousKeywords = {"update", "delete", "insert", "select", "and", "or"};
		    for(String keyword : dangerousKeywords) {
		      dados = dados.replaceAll("(?i)\\b" + keyword + "\\b", " ");   
		    }
		    dados = dados.replaceAll("\\$(\\w+)\\$", " ");
		    dados = dados.replace("'", "`").replace("$$", "");
		    
		  }
		  return dados;
		}
	
	public static void main(String[] args) {
		
		var json = "{\r\n"
				+ "  \"event\": {\r\n"
				+ "    \"name\": \"remove_signer\",\r\n"
				+ "    \"data\": {\r\n"
				+ "      \"user\": {\r\n"
				+ "        \"email\": \"leonardo.rocha@ectare.com.br\",\r\n"
				+ "        \"name\": \"Leonardo Godoy Rocha\"\r\n"
				+ "      },\r\n"
				+ "      \"account\": { \"key\": \"7517be57-04e6-4c33-a65f-218311ebb50b\" },\r\n"
				+ "      \"signers\": [\r\n"
				+ "        {\r\n"
				+ "          \"sign_as\": \"witness\",\r\n"
				+ "          \"key\": \"23aa5776-8b4a-410c-95d0-f894b60b4bb3\",\r\n"
				+ "          \"email\": \"ana.arantes@ectare.com.br\",\r\n"
				+ "          \"name\": \"Ana Marta Arantes Caetano\",\r\n"
				+ "          \"birthday\": null,\r\n"
				+ "          \"documentation\": null,\r\n"
				+ "          \"has_documentation\": false,\r\n"
				+ "          \"created_at\": \"2024-01-19T16:29:33.587-03:00\",\r\n"
				+ "          \"auths\": [\"email\"],\r\n"
				+ "          \"selfie_enabled\": false,\r\n"
				+ "          \"handwritten_enabled\": false,\r\n"
				+ "          \"official_document_enabled\": false,\r\n"
				+ "          \"liveness_enabled\": false,\r\n"
				+ "          \"facial_biometrics_enabled\": false,\r\n"
				+ "          \"communicate_by\": \"email\",\r\n"
				+ "          \"list_key\": \"42b72bf4-1150-4f61-9346-a6e6ea446da1\",\r\n"
				+ "          \"url\": \"https://app.clicksign.com/sign/94b2bd7b-fffd-4fa9-b0a2-7a195706e575\",\r\n"
				+ "          \"read_receipts?\": false\r\n"
				+ "        }\r\n"
				+ "      ]\r\n"
				+ "    },\r\n"
				+ "    \"occurred_at\": \"2024-01-19T16:31:16.037-03:00\"\r\n"
				+ "  },\r\n"
				+ "  \"document\": {\r\n"
				+ "    \"key\": \"1c215ef6-f92f-4f81-8477-25cdd726b33e\",\r\n"
				+ "    \"account_key\": \"7517be57-04e6-4c33-a65f-218311ebb50b\",\r\n"
				+ "    \"path\": \"/CPRF_Generica/CPRF_JoseTestador_3653.docx\",\r\n"
				+ "    \"filename\": \"CPRF_JoseTestador_3653.docx\",\r\n"
				+ "    \"uploaded_at\": \"2024-01-19T19:29:32.248Z\",\r\n"
				+ "    \"updated_at\": \"2024-01-19T19:31:16.013Z\",\r\n"
				+ "    \"finished_at\": null,\r\n"
				+ "    \"deadline_at\": \"2024-02-08T23:59:59.000-03:00\",\r\n"
				+ "    \"status\": \"running\",\r\n"
				+ "    \"auto_close\": true,\r\n"
				+ "    \"locale\": \"pt-BR\",\r\n"
				+ "    \"metadata\": {},\r\n"
				+ "    \"sequence_enabled\": true,\r\n"
				+ "    \"signable_group\": 2,\r\n"
				+ "    \"remind_interval\": null,\r\n"
				+ "    \"block_after_refusal\": true,\r\n"
				+ "    \"preview\": true,\r\n"
				+ "    \"downloads\": {\r\n"
				+ "      \"original_file_url\": \"https://clicksign-content-production.s3.amazonaws.com/2024/01/19/19/29/32/db63a983-fa53-4cff-bcab-bd8ebf21ade9/CPRF_JoseTestador_3653.docx?X-Amz-Expires=300\\u0026X-Amz-Date=20240119T193116Z\\u0026X-Amz-Security-Token=IQoJb3JpZ2luX2VjEEsaCXVzLWVhc3QtMSJIMEYCIQCppmEsO5l%2Bs90cvW8Ym2jXeqOm68J%2BkleSfB3YDg2qCwIhAOD1qjLtk6k7y2GnnBeEBOUnNtwGwLvKlgDy1CY7uMfqKroFCPT%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQABoMNjk2OTc2MzYwOTY3Igy2VEMd3EjeeeAO5pgqjgVtJ4zn4D7mgIUA1%2FfhwcECwESbV2deEMGo%2FdwFwYfIuQFa3LiDEUmL%2BT3xXTTFZflyqmruKNiaKXQDuo0wunrkaTicjSwx0EFLBLn0JjEZYTpbOQCGS1Iv4%2Fde1jL4JfJqubv2C91eYso8ZGcAdaaZgTJmgmto%2F4CfsjxPtEOs23JRBM1Se7TYzCnK0Pjc60k2Q9DxvBULslaWf9%2FeqxVlHfRl2f9P9ittM17DVBHYvZvQ9g%2B1U1KYy8spOvgYAZgJmv7%2BRJD4v9m%2BQbGSZWGFdmkL8yXl0xfk8Ny3YRyTzVlMTNAgFO53pF4lTvqd7x9H2dOqLn%2BLjs35Kf67%2FMCeN%2FWvfMeFaeXG%2BCpPpG7jGgGC8B43wXTwu40doJ1yTABZs8GErTLD4Dbgx1YrEhUHW0OQ9h%2BAi0sKoCfPLLWXlTghht0hfEWaIvHBnCPCU%2B5CPcQZktlfzYCXEVWmPZbrHL1u15O9IqY4DeLeNRrJfJ%2BCLiNYEYwRyvvBYESjFTCWixzD8cTMGQC9xdqEoHlLSKfsSSCpDblKoEOaQ%2BR0vnWvuWd9MQ1x7JuIPGRSl7UeuHGw%2Fk%2BU1nfrpR3NULbmoKD%2FYD%2BONn0nXxDQn%2BPhU9sXPs8JfZ8%2Fplcd2J244EbCVpdc3i2yrB8l5zix4wmLwdXd0qu6GM1Jdfe%2FpT1%2BvWySsJM78Z%2F92AL06XRaOso%2F8S6ykZ2gWx%2FN3QNtO9RXRHiD%2FHsazbhOcjZy5y4pITLW%2B7chzo0kktnz68j9TvQRYDVhajpwY5EfttD7gi%2FHXiJ16vE9gTZ0JbS33NaOAWLpOxevdLeHtasRpCeseiLjemrJ6APPinzSP%2BtdM%2FaTQazF13RM7mGzl%2BFN0aowxIWrrQY6sAHgnX4LYPTb3TSjR513mQjjwGDbNoGfMLwFrYYvSFwvQSLiislWLjqRzEbkvvaao%2BHPX2uOZRL3%2Fsvcl4w8Jr3SXij0mfwqc3rUIaYFjEnRcTI2dKAn4nkzrdxU94w26Fz1l7UZ1JX2zpJbkAo5OtI6v8kD3hSv3dWFR8lTC7H7pHqVcxMSQOAK56fQdnUUjH4dcDXvxFxHVITz%2FaE4%2F58jj1vChtSL4hOYCiPTb3RXlg%3D%3D\\u0026X-Amz-Algorithm=AWS4-HMAC-SHA256\\u0026X-Amz-Credential=ASIA2ERYHIYDWZQVI2ZR%2F20240119%2Fus-east-1%2Fs3%2Faws4_request\\u0026X-Amz-SignedHeaders=host\\u0026X-Amz-Signature=119972bb5ddefd24f88f348409c1961815637aeabecb1aa605f4f90abab1a159\"\r\n"
				+ "    },\r\n"
				+ "    \"template\": {\r\n"
				+ "      \"key\": \"d8f04cf6-979d-46e4-bac9-828f21d2c0ee\",\r\n"
				+ "      \"data\": {\r\n"
				+ "        \"numerowarrant\": 0,\r\n"
				+ "        \"nome_produtor\": \"JosÃ© Testador\",\r\n"
				+ "        \"cidade\": \"Sao Sebastiao do Paraiso\",\r\n"
				+ "        \"estado\": \"MG\",\r\n"
				+ "        \"idpessoaarmazem\": 112,\r\n"
				+ "        \"numlote_1\": \"\",\r\n"
				+ "        \"quantidade_amarrada_1\": \"\",\r\n"
				+ "        \"descricao_lote_1\": \"\",\r\n"
				+ "        \"numlote_2\": \"\",\r\n"
				+ "        \"quantidade_amarrada_2\": \"\",\r\n"
				+ "        \"descricao_lote_2\": \"\",\r\n"
				+ "        \"numlote_3\": \"\",\r\n"
				+ "        \"quantidade_amarrada_3\": \"\",\r\n"
				+ "        \"descricao_lote_3\": \"\",\r\n"
				+ "        \"numlote_4\": \"\",\r\n"
				+ "        \"quantidade_amarrada_4\": \"\",\r\n"
				+ "        \"descricao_lote_4\": \"\",\r\n"
				+ "        \"numlote_5\": \"\",\r\n"
				+ "        \"quantidade_amarrada_5\": \"\",\r\n"
				+ "        \"descricao_lote_5\": \"\",\r\n"
				+ "        \"numlote_6\": \"\",\r\n"
				+ "        \"quantidade_amarrada_6\": \"\",\r\n"
				+ "        \"descricao_lote_6\": \"\",\r\n"
				+ "        \"numlote_7\": \"\",\r\n"
				+ "        \"quantidade_amarrada_7\": \"\",\r\n"
				+ "        \"descricao_lote_7\": \"\",\r\n"
				+ "        \"numlote_8\": \"\",\r\n"
				+ "        \"quantidade_amarrada_8\": \"\",\r\n"
				+ "        \"descricao_lote_8\": \"\",\r\n"
				+ "        \"numlote_9\": \"\",\r\n"
				+ "        \"quantidade_amarrada_9\": \"\",\r\n"
				+ "        \"descricao_lote_9\": \"\",\r\n"
				+ "        \"numlote_10\": \"\",\r\n"
				+ "        \"quantidade_amarrada_10\": \"\",\r\n"
				+ "        \"descricao_lote_10\": \"\",\r\n"
				+ "        \"numlote_11\": \"\",\r\n"
				+ "        \"quantidade_amarrada_11\": \"\",\r\n"
				+ "        \"descricao_lote_11\": \"\",\r\n"
				+ "        \"numlote_12\": \"\",\r\n"
				+ "        \"quantidade_amarrada_12\": \"\",\r\n"
				+ "        \"descricao_lote_12\": \"\",\r\n"
				+ "        \"numlote_13\": \"\",\r\n"
				+ "        \"quantidade_amarrada_13\": \"\",\r\n"
				+ "        \"descricao_lote_13\": \"\",\r\n"
				+ "        \"numlote_14\": \"\",\r\n"
				+ "        \"quantidade_amarrada_14\": \"\",\r\n"
				+ "        \"descricao_lote_14\": \"\",\r\n"
				+ "        \"numlote_15\": \"\",\r\n"
				+ "        \"quantidade_amarrada_15\": \"\",\r\n"
				+ "        \"descricao_lote_15\": \"\",\r\n"
				+ "        \"numlote_16\": \"\",\r\n"
				+ "        \"quantidade_amarrada_16\": \"\",\r\n"
				+ "        \"descricao_lote_16\": \"\",\r\n"
				+ "        \"pesobruto\": 0.0,\r\n"
				+ "        \"pesoliquido\": 0.0,\r\n"
				+ "        \"valortotal\": 0.01,\r\n"
				+ "        \"valortotal_extenso\": \"Um Centavo) com vencimento em 15/02/2024\",\r\n"
				+ "        \"produto\": \"Bovinos\",\r\n"
				+ "        \"quantidade\": \"0,0000\",\r\n"
				+ "        \"qualidade_produto\": \"terminados para abate. \",\r\n"
				+ "        \"cedula_produto_rural\": \"3653/2024\",\r\n"
				+ "        \"data_emissao\": \"19/01/2024\",\r\n"
				+ "        \"valor_total_formatado\": \"R$ 0,01\",\r\n"
				+ "        \"data_vencimento_final\": \"15/02/2024\",\r\n"
				+ "        \"taxa_pagamento\": \"1,00\",\r\n"
				+ "        \"taxa_pagamento_alterada\": \"2,00\",\r\n"
				+ "        \"avalistas\": \" \",\r\n"
				+ "        \"testemunha1\": \"Ana Marta Arantes Caetano\",\r\n"
				+ "        \"testemunha2\": \"Samuel Vilas Boas Coimbra\",\r\n"
				+ "        \"doc1\": \"100.134.736-62\",\r\n"
				+ "        \"doc2\": \"149.233.486-31\",\r\n"
				+ "        \"numero_conta\": \"0\",\r\n"
				+ "        \"dv_conta\": \"0\",\r\n"
				+ "        \"agencia_conta\": \"0\",\r\n"
				+ "        \"nome_banco\": \"Banco 001 - Banco do Brasil S.A.\",\r\n"
				+ "        \"profissao\": \"\",\r\n"
				+ "        \"lavoura_nome_imovel\": \"Fazenda AraÃ§atuba\",\r\n"
				+ "        \"lavoura_matricula\": \"\\nMatrÃ­cula: 111222333444\\nNÃºmero do ImÃ³vel na Receita Federal (NIRF): 9.999.999-9\",\r\n"
				+ "        \"lavoura_matricula_localizacao_produto\": \"111222333444\",\r\n"
				+ "        \"lavoura_area_total\": \"3441,89 Ha\",\r\n"
				+ "        \"lavoura_area_cultivada\": \"2000 Ha\",\r\n"
				+ "        \"lavoura_cartorio\": \"\\nCartÃ³rio de Registro de ImÃ³veis: CartÃ³rio ParaÃ­so\",\r\n"
				+ "        \"lavoura_municipio\": \"Santa FÃ© do Araguaia\",\r\n"
				+ "        \"lavoura_uf\": \"TO\",\r\n"
				+ "        \"lavoura_cep\": \"37950-000\",\r\n"
				+ "        \"lavoura_proprietario_arrendatario\": \"JosÃ© Testador\",\r\n"
				+ "        \"lavoura_cpf_cnpj\": \"27138253000182\",\r\n"
				+ "        \"lavoura_nacionalidade\": \"\",\r\n"
				+ "        \"lavoura_estado_civil\": \"\",\r\n"
				+ "        \"lavoura_profissao\": \"\",\r\n"
				+ "        \"lavoura_valor_referencia\": \"R$ 0,01\",\r\n"
				+ "        \"lavoura_valor_referencia_extenso\": \"Um Centavo) com vencimento em 15/02/2024\",\r\n"
				+ "        \"lavoura_preco_referencia\": \"R$ 251,1000\",\r\n"
				+ "        \"lavoura_data_apuracao\": \"19/01/2024\",\r\n"
				+ "        \"lavoura_instituicao_referencia\": \"CEPEA\",\r\n"
				+ "        \"lavoura_arrendatario_rg\": \", portador da cÃ©dula de identidade \",\r\n"
				+ "        \"lavoura_grau_penhor\": \"N/A\",\r\n"
				+ "        \"conta_numero\": \"0-0\",\r\n"
				+ "        \"conta_agencia\": \"0\",\r\n"
				+ "        \"conta_banco\": \"Banco 001 - Banco do Brasil S.A.\",\r\n"
				+ "        \"lavoura_inscricao\": \"devidamente inscrita na matrÃ­cula 111222333444 no CartÃ³rio de Registro de ImÃ³veis CartÃ³rio ParaÃ­so\",\r\n"
				+ "        \"lavoura_coordenada_geografica\": \"\",\r\n"
				+ "        \"lavoura_endereco_proprietario\": \", residente e domiciliado a Rua Pimenta de Teste, 100, Centro, Santa FÃ© do Araguaia, Estado MG, CEP 37950-000.\",\r\n"
				+ "        \"credor\": \"E-CTARE PAY SERVIÃOS DE GESTÃO DE PAGAMENTOS S/A, inscrito no CNPJ nÂº 34.536.749/0001-70 (E-CTARE), com sede na Avenida LituÃ¢nia, nÂº 150, sala 3 â Jardim Europa CEP: 37950-000, na cidade de SÃ£o SebastiÃ£o do ParaÃ­so, Estado de Minas Gerais, endereÃ§o eletrÃ´nico livia@ectare.com.br e suporte@ectare.com.br. \",\r\n"
				+ "        \"safra\": \"\",\r\n"
				+ "        \"safra_penhor\": \"\",\r\n"
				+ "        \"nacionalidade\": \"brasileira,\",\r\n"
				+ "        \"estado_civil\": \"Solteiro(a)\",\r\n"
				+ "        \"cpf_produtor\": \"123.123.777-56\",\r\n"
				+ "        \"data_nascimento_produtor\": \"2000-10-10 00:00:00\",\r\n"
				+ "        \"endereÃ§o_produtor\": \"Rua das Flores 0,Centro\",\r\n"
				+ "        \"cidade_produtor\": \"Sao Sebastiao do Paraiso\",\r\n"
				+ "        \"cep\": \"37950-000\",\r\n"
				+ "        \"uf\": \"MG\",\r\n"
				+ "        \"email_produtor\": \"ely@agely.com.br\",\r\n"
				+ "        \"telefone_produtor\": \"(35) 99996-4999\",\r\n"
				+ "        \"data_hoje_extenso\": \"19 de Janeiro de 2024\",\r\n"
				+ "        \"forma_pagamento\": \"Uma parcela final de \",\r\n"
				+ "        \"recurso_liquidos\": \"R$ 0,01\",\r\n"
				+ "        \"recursos_liquido_extenso\": \"Um Centavo\",\r\n"
				+ "        \"valor_penhor\": \"0,01\",\r\n"
				+ "        \"valor_penhor_extenso\": \"Um Centavo\",\r\n"
				+ "        \"quantidade_penhor\": \"0,0001\",\r\n"
				+ "        \"valor_unitario\": \"251,1000\",\r\n"
				+ "        \"valor_unitario_extenso\": \"Duzentos e Cinquenta e Um reais e Dez Centavos\",\r\n"
				+ "        \"preco_produto\": \"R$ 251,1000\",\r\n"
				+ "        \"preco_produto_extenso\": \"duzentos e cinquenta e um reais e dez centavos\",\r\n"
				+ "        \"unidade_produto\": \"Arroba(s)\",\r\n"
				+ "        \"dados_emitente\": \"JosÃ© Testador, brasileira, Solteiro(a),  inscrito no CPF/MF nÂº. 123.123.777-56 , portador da cÃ©dula de identidade 123456, residente e domiciliado na Rua das Flores 0,Centro, CEP: 37950-000, na Cidade de Sao Sebastiao do Paraiso, Estado de MG, endereÃ§o eletrÃ´nico ely@agely.com.br\"\r\n"
				+ "      }\r\n"
				+ "    },\r\n"
				+ "    \"signers\": [\r\n"
				+ "      {\r\n"
				+ "        \"list_key\": \"a8fd47f8-a8ea-420e-8040-b585ed89c2fd\",\r\n"
				+ "        \"key\": \"be7b082a-2e75-46a1-ba2f-d5168c463ef2\",\r\n"
				+ "        \"request_signature_key\": \"7bd66b0a-5c22-471a-84a2-6d1666672244\",\r\n"
				+ "        \"email\": \"\",\r\n"
				+ "        \"name\": \"Leonardo Rocha\",\r\n"
				+ "        \"has_documentation\": true,\r\n"
				+ "        \"documentation\": \"135.694.866-99\",\r\n"
				+ "        \"birthday\": \"1998-03-18\",\r\n"
				+ "        \"phone_number\": \"35988340372\",\r\n"
				+ "        \"sign_as\": \"sign\",\r\n"
				+ "        \"delivery\": \"email\",\r\n"
				+ "        \"group\": 2,\r\n"
				+ "        \"refusable\": false,\r\n"
				+ "        \"url\": \"https://app.clicksign.com/sign/7bd66b0a-5c22-471a-84a2-6d1666672244\",\r\n"
				+ "        \"auths\": [\"whatsapp\"],\r\n"
				+ "        \"created_at\": \"2023-05-30T22:05:57.114Z\"\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"events\": [\r\n"
				+ "      {\r\n"
				+ "        \"name\": \"remove_signer\",\r\n"
				+ "        \"data\": {\r\n"
				+ "          \"user\": {\r\n"
				+ "            \"email\": \"leonardo.rocha@ectare.com.br\",\r\n"
				+ "            \"name\": \"Leonardo Godoy Rocha\"\r\n"
				+ "          },\r\n"
				+ "          \"account\": { \"key\": \"7517be57-04e6-4c33-a65f-218311ebb50b\" },\r\n"
				+ "          \"signers\": [\r\n"
				+ "            {\r\n"
				+ "              \"sign_as\": \"witness\",\r\n"
				+ "              \"key\": \"23aa5776-8b4a-410c-95d0-f894b60b4bb3\",\r\n"
				+ "              \"email\": \"ana.arantes@ectare.com.br\",\r\n"
				+ "              \"name\": \"Ana Marta Arantes Caetano\",\r\n"
				+ "              \"birthday\": null,\r\n"
				+ "              \"documentation\": null,\r\n"
				+ "              \"has_documentation\": false,\r\n"
				+ "              \"created_at\": \"2024-01-19T16:29:33.587-03:00\",\r\n"
				+ "              \"auths\": [\"email\"],\r\n"
				+ "              \"selfie_enabled\": false,\r\n"
				+ "              \"handwritten_enabled\": false,\r\n"
				+ "              \"official_document_enabled\": false,\r\n"
				+ "              \"liveness_enabled\": false,\r\n"
				+ "              \"facial_biometrics_enabled\": false,\r\n"
				+ "              \"communicate_by\": \"email\",\r\n"
				+ "              \"list_key\": \"42b72bf4-1150-4f61-9346-a6e6ea446da1\",\r\n"
				+ "              \"url\": \"https://app.clicksign.com/sign/94b2bd7b-fffd-4fa9-b0a2-7a195706e575\",\r\n"
				+ "              \"read_receipts?\": false\r\n"
				+ "            }\r\n"
				+ "          ]\r\n"
				+ "        },\r\n"
				+ "        \"occurred_at\": \"2024-01-19T19:31:16.037Z\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"name\": \"remove_signer\",\r\n"
				+ "        \"data\": {\r\n"
				+ "          \"user\": {\r\n"
				+ "            \"email\": \"leonardo.rocha@ectare.com.br\",\r\n"
				+ "            \"name\": \"Leonardo Godoy Rocha\"\r\n"
				+ "          },\r\n"
				+ "          \"account\": { \"key\": \"7517be57-04e6-4c33-a65f-218311ebb50b\" },\r\n"
				+ "          \"signers\": [\r\n"
				+ "            {\r\n"
				+ "              \"sign_as\": \"sign\",\r\n"
				+ "              \"key\": \"ccfd5350-a7a3-43e7-bb01-de72590ccef0\",\r\n"
				+ "              \"email\": \"ely@agely.com.br\",\r\n"
				+ "              \"name\": \"Jose Testador\",\r\n"
				+ "              \"birthday\": null,\r\n"
				+ "              \"documentation\": null,\r\n"
				+ "              \"has_documentation\": false,\r\n"
				+ "              \"created_at\": \"2024-01-19T16:29:33.019-03:00\",\r\n"
				+ "              \"auths\": [\"whatsapp\"],\r\n"
				+ "              \"selfie_enabled\": true,\r\n"
				+ "              \"handwritten_enabled\": false,\r\n"
				+ "              \"official_document_enabled\": false,\r\n"
				+ "              \"liveness_enabled\": false,\r\n"
				+ "              \"facial_biometrics_enabled\": false,\r\n"
				+ "              \"communicate_by\": \"email\",\r\n"
				+ "              \"phone_number\": \"35988340372\",\r\n"
				+ "              \"phone_number_hash\": \"48827ec0561b87e41be2f88673e68a6a086291547832db90520e4446601a634c\",\r\n"
				+ "              \"list_key\": \"61f867f2-6cfd-42af-b62d-7ec45c3b9805\",\r\n"
				+ "              \"url\": \"https://app.clicksign.com/sign/f8fd3e35-4df8-43a4-aabf-a7c6bfffd969\",\r\n"
				+ "              \"read_receipts?\": false\r\n"
				+ "            }\r\n"
				+ "          ]\r\n"
				+ "        },\r\n"
				+ "        \"occurred_at\": \"2024-01-19T19:31:12.148Z\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"name\": \"remove_signer\",\r\n"
				+ "        \"data\": {\r\n"
				+ "          \"user\": {\r\n"
				+ "            \"email\": \"leonardo.rocha@ectare.com.br\",\r\n"
				+ "            \"name\": \"Leonardo Godoy Rocha\"\r\n"
				+ "          },\r\n"
				+ "          \"account\": { \"key\": \"7517be57-04e6-4c33-a65f-218311ebb50b\" },\r\n"
				+ "          \"signers\": [\r\n"
				+ "            {\r\n"
				+ "              \"sign_as\": \"sign\",\r\n"
				+ "              \"key\": \"4ca3daa5-a85b-4cf1-8e3a-d797475bd374\",\r\n"
				+ "              \"email\": \"livia@peneiraalta.com.br\",\r\n"
				+ "              \"name\": \"FERNANDO MONTANS ALVARENGA\",\r\n"
				+ "              \"birthday\": null,\r\n"
				+ "              \"documentation\": \"048.323.786-86\",\r\n"
				+ "              \"has_documentation\": true,\r\n"
				+ "              \"created_at\": \"2024-01-19T16:29:34.997-03:00\",\r\n"
				+ "              \"auths\": [\"icp_brasil\"],\r\n"
				+ "              \"selfie_enabled\": false,\r\n"
				+ "              \"handwritten_enabled\": false,\r\n"
				+ "              \"official_document_enabled\": false,\r\n"
				+ "              \"liveness_enabled\": false,\r\n"
				+ "              \"facial_biometrics_enabled\": false,\r\n"
				+ "              \"communicate_by\": \"email\",\r\n"
				+ "              \"list_key\": \"dfe56943-322a-44ad-ba59-2e091d226c14\",\r\n"
				+ "              \"url\": \"https://app.clicksign.com/sign/8c10c7e8-b262-41cc-b518-9bd55b9c7acf\",\r\n"
				+ "              \"read_receipts?\": false\r\n"
				+ "            }\r\n"
				+ "          ]\r\n"
				+ "        },\r\n"
				+ "        \"occurred_at\": \"2024-01-19T19:31:08.932Z\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"name\": \"remove_signer\",\r\n"
				+ "        \"data\": {\r\n"
				+ "          \"user\": {\r\n"
				+ "            \"email\": \"leonardo.rocha@ectare.com.br\",\r\n"
				+ "            \"name\": \"Leonardo Godoy Rocha\"\r\n"
				+ "          },\r\n"
				+ "          \"account\": { \"key\": \"7517be57-04e6-4c33-a65f-218311ebb50b\" },\r\n"
				+ "          \"signers\": [\r\n"
				+ "            {\r\n"
				+ "              \"sign_as\": \"sign\",\r\n"
				+ "              \"key\": \"f5375503-74ab-4411-89ca-e19852f99bcf\",\r\n"
				+ "              \"email\": \"paulo.viola@ectare.com.br\",\r\n"
				+ "              \"name\": \"Paulo Vitor Viola\",\r\n"
				+ "              \"birthday\": null,\r\n"
				+ "              \"documentation\": \"720.397.791-91\",\r\n"
				+ "              \"has_documentation\": true,\r\n"
				+ "              \"created_at\": \"2024-01-19T16:29:35.778-03:00\",\r\n"
				+ "              \"auths\": [\"icp_brasil\"],\r\n"
				+ "              \"selfie_enabled\": false,\r\n"
				+ "              \"handwritten_enabled\": false,\r\n"
				+ "              \"official_document_enabled\": false,\r\n"
				+ "              \"liveness_enabled\": false,\r\n"
				+ "              \"facial_biometrics_enabled\": false,\r\n"
				+ "              \"communicate_by\": \"email\",\r\n"
				+ "              \"list_key\": \"f8647dbb-0b0f-4f4e-8989-00f91df8a897\",\r\n"
				+ "              \"url\": \"https://app.clicksign.com/sign/e1eb9aad-0646-4544-8c39-7f114332730b\",\r\n"
				+ "              \"read_receipts?\": false\r\n"
				+ "            }\r\n"
				+ "          ]\r\n"
				+ "        },\r\n"
				+ "        \"occurred_at\": \"2024-01-19T19:31:05.457Z\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"name\": \"remove_signer\",\r\n"
				+ "        \"data\": {\r\n"
				+ "          \"user\": {\r\n"
				+ "            \"email\": \"leonardo.rocha@ectare.com.br\",\r\n"
				+ "            \"name\": \"Leonardo Godoy Rocha\"\r\n"
				+ "          },\r\n"
				+ "          \"account\": { \"key\": \"7517be57-04e6-4c33-a65f-218311ebb50b\" },\r\n"
				+ "          \"signers\": [\r\n"
				+ "            {\r\n"
				+ "              \"sign_as\": \"witness\",\r\n"
				+ "              \"key\": \"0e8ab436-7c7f-40cb-96b9-527aeb054a8a\",\r\n"
				+ "              \"email\": \"samuel.coimbra@ectare.com.br\",\r\n"
				+ "              \"name\": \"Samuel Vilas Boas Coimbra\",\r\n"
				+ "              \"birthday\": null,\r\n"
				+ "              \"documentation\": null,\r\n"
				+ "              \"has_documentation\": false,\r\n"
				+ "              \"created_at\": \"2024-01-19T16:29:34.345-03:00\",\r\n"
				+ "              \"auths\": [\"whatsapp\"],\r\n"
				+ "              \"selfie_enabled\": false,\r\n"
				+ "              \"handwritten_enabled\": false,\r\n"
				+ "              \"official_document_enabled\": false,\r\n"
				+ "              \"liveness_enabled\": false,\r\n"
				+ "              \"facial_biometrics_enabled\": false,\r\n"
				+ "              \"communicate_by\": \"email\",\r\n"
				+ "              \"phone_number\": \"35997334880\",\r\n"
				+ "              \"phone_number_hash\": \"9d0590df2e97c2de5eb38fc9e347140cf2cf17e39c4682da9da4549afd559d7f\",\r\n"
				+ "              \"list_key\": \"6f66227a-58e9-47ec-9888-5d48b1bd0890\",\r\n"
				+ "              \"url\": \"https://app.clicksign.com/sign/352ef035-ce04-495e-a21c-d46cc427983d\",\r\n"
				+ "              \"read_receipts?\": false\r\n"
				+ "            }\r\n"
				+ "          ]\r\n"
				+ "        },\r\n"
				+ "        \"occurred_at\": \"2024-01-19T19:31:01.158Z\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"name\": \"add_signer\",\r\n"
				+ "        \"data\": {\r\n"
				+ "          \"user\": {\r\n"
				+ "            \"email\": \"leonardo.rocha@ectare.com.br\",\r\n"
				+ "            \"name\": \"Leonardo Godoy Rocha\"\r\n"
				+ "          },\r\n"
				+ "          \"account\": { \"key\": \"7517be57-04e6-4c33-a65f-218311ebb50b\" },\r\n"
				+ "          \"signers\": [\r\n"
				+ "            {\r\n"
				+ "              \"sign_as\": \"sign\",\r\n"
				+ "              \"key\": \"be7b082a-2e75-46a1-ba2f-d5168c463ef2\",\r\n"
				+ "              \"email\": \"\",\r\n"
				+ "              \"name\": \"Leonardo Rocha\",\r\n"
				+ "              \"birthday\": \"1998-03-18\",\r\n"
				+ "              \"documentation\": \"135.694.866-99\",\r\n"
				+ "              \"has_documentation\": true,\r\n"
				+ "              \"created_at\": \"2023-05-30T19:05:57.114-03:00\",\r\n"
				+ "              \"auths\": [\"whatsapp\"],\r\n"
				+ "              \"selfie_enabled\": false,\r\n"
				+ "              \"handwritten_enabled\": false,\r\n"
				+ "              \"official_document_enabled\": false,\r\n"
				+ "              \"liveness_enabled\": false,\r\n"
				+ "              \"facial_biometrics_enabled\": false,\r\n"
				+ "              \"communicate_by\": \"whatsapp\",\r\n"
				+ "              \"phone_number\": \"35988340372\",\r\n"
				+ "              \"phone_number_hash\": \"48827ec0561b87e41be2f88673e68a6a086291547832db90520e4446601a634c\",\r\n"
				+ "              \"list_key\": \"a8fd47f8-a8ea-420e-8040-b585ed89c2fd\",\r\n"
				+ "              \"url\": \"https://app.clicksign.com/sign/be7b082a-2e75-46a1-ba2f-d5168c463ef2\",\r\n"
				+ "              \"read_receipts?\": false\r\n"
				+ "            }\r\n"
				+ "          ]\r\n"
				+ "        },\r\n"
				+ "        \"occurred_at\": \"2024-01-19T19:30:54.275Z\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"name\": \"add_signer\",\r\n"
				+ "        \"data\": {\r\n"
				+ "          \"user\": {\r\n"
				+ "            \"email\": \"suporte@ectare.com.br\",\r\n"
				+ "            \"name\": \"Samuel Vilas Boas Coimbra\"\r\n"
				+ "          },\r\n"
				+ "          \"account\": { \"key\": \"7517be57-04e6-4c33-a65f-218311ebb50b\" },\r\n"
				+ "          \"signers\": [\r\n"
				+ "            {\r\n"
				+ "              \"sign_as\": \"sign\",\r\n"
				+ "              \"key\": \"f5375503-74ab-4411-89ca-e19852f99bcf\",\r\n"
				+ "              \"email\": \"paulo.viola@ectare.com.br\",\r\n"
				+ "              \"name\": \"Paulo Vitor Viola\",\r\n"
				+ "              \"birthday\": null,\r\n"
				+ "              \"documentation\": \"720.397.791-91\",\r\n"
				+ "              \"has_documentation\": true,\r\n"
				+ "              \"created_at\": \"2024-01-19T16:29:35.778-03:00\",\r\n"
				+ "              \"auths\": [\"icp_brasil\"],\r\n"
				+ "              \"selfie_enabled\": false,\r\n"
				+ "              \"handwritten_enabled\": false,\r\n"
				+ "              \"official_document_enabled\": false,\r\n"
				+ "              \"liveness_enabled\": false,\r\n"
				+ "              \"facial_biometrics_enabled\": false,\r\n"
				+ "              \"communicate_by\": \"email\",\r\n"
				+ "              \"list_key\": \"f8647dbb-0b0f-4f4e-8989-00f91df8a897\",\r\n"
				+ "              \"url\": \"https://app.clicksign.com/sign/f5375503-74ab-4411-89ca-e19852f99bcf\",\r\n"
				+ "              \"read_receipts?\": false\r\n"
				+ "            }\r\n"
				+ "          ]\r\n"
				+ "        },\r\n"
				+ "        \"occurred_at\": \"2024-01-19T19:29:36.019Z\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"name\": \"add_signer\",\r\n"
				+ "        \"data\": {\r\n"
				+ "          \"user\": {\r\n"
				+ "            \"email\": \"suporte@ectare.com.br\",\r\n"
				+ "            \"name\": \"Samuel Vilas Boas Coimbra\"\r\n"
				+ "          },\r\n"
				+ "          \"account\": { \"key\": \"7517be57-04e6-4c33-a65f-218311ebb50b\" },\r\n"
				+ "          \"signers\": [\r\n"
				+ "            {\r\n"
				+ "              \"sign_as\": \"sign\",\r\n"
				+ "              \"key\": \"4ca3daa5-a85b-4cf1-8e3a-d797475bd374\",\r\n"
				+ "              \"email\": \"livia@peneiraalta.com.br\",\r\n"
				+ "              \"name\": \"FERNANDO MONTANS ALVARENGA\",\r\n"
				+ "              \"birthday\": null,\r\n"
				+ "              \"documentation\": \"048.323.786-86\",\r\n"
				+ "              \"has_documentation\": true,\r\n"
				+ "              \"created_at\": \"2024-01-19T16:29:34.997-03:00\",\r\n"
				+ "              \"auths\": [\"icp_brasil\"],\r\n"
				+ "              \"selfie_enabled\": false,\r\n"
				+ "              \"handwritten_enabled\": false,\r\n"
				+ "              \"official_document_enabled\": false,\r\n"
				+ "              \"liveness_enabled\": false,\r\n"
				+ "              \"facial_biometrics_enabled\": false,\r\n"
				+ "              \"communicate_by\": \"email\",\r\n"
				+ "              \"list_key\": \"dfe56943-322a-44ad-ba59-2e091d226c14\",\r\n"
				+ "              \"url\": \"https://app.clicksign.com/sign/4ca3daa5-a85b-4cf1-8e3a-d797475bd374\",\r\n"
				+ "              \"read_receipts?\": false\r\n"
				+ "            }\r\n"
				+ "          ]\r\n"
				+ "        },\r\n"
				+ "        \"occurred_at\": \"2024-01-19T19:29:35.213Z\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"name\": \"add_signer\",\r\n"
				+ "        \"data\": {\r\n"
				+ "          \"user\": {\r\n"
				+ "            \"email\": \"suporte@ectare.com.br\",\r\n"
				+ "            \"name\": \"Samuel Vilas Boas Coimbra\"\r\n"
				+ "          },\r\n"
				+ "          \"account\": { \"key\": \"7517be57-04e6-4c33-a65f-218311ebb50b\" },\r\n"
				+ "          \"signers\": [\r\n"
				+ "            {\r\n"
				+ "              \"sign_as\": \"witness\",\r\n"
				+ "              \"key\": \"0e8ab436-7c7f-40cb-96b9-527aeb054a8a\",\r\n"
				+ "              \"email\": \"samuel.coimbra@ectare.com.br\",\r\n"
				+ "              \"name\": \"Samuel Vilas Boas Coimbra\",\r\n"
				+ "              \"birthday\": null,\r\n"
				+ "              \"documentation\": null,\r\n"
				+ "              \"has_documentation\": false,\r\n"
				+ "              \"created_at\": \"2024-01-19T16:29:34.345-03:00\",\r\n"
				+ "              \"auths\": [\"whatsapp\"],\r\n"
				+ "              \"selfie_enabled\": false,\r\n"
				+ "              \"handwritten_enabled\": false,\r\n"
				+ "              \"official_document_enabled\": false,\r\n"
				+ "              \"liveness_enabled\": false,\r\n"
				+ "              \"facial_biometrics_enabled\": false,\r\n"
				+ "              \"communicate_by\": \"email\",\r\n"
				+ "              \"phone_number\": \"35997334880\",\r\n"
				+ "              \"phone_number_hash\": \"9d0590df2e97c2de5eb38fc9e347140cf2cf17e39c4682da9da4549afd559d7f\",\r\n"
				+ "              \"list_key\": \"6f66227a-58e9-47ec-9888-5d48b1bd0890\",\r\n"
				+ "              \"url\": \"https://app.clicksign.com/sign/0e8ab436-7c7f-40cb-96b9-527aeb054a8a\",\r\n"
				+ "              \"read_receipts?\": false\r\n"
				+ "            }\r\n"
				+ "          ]\r\n"
				+ "        },\r\n"
				+ "        \"occurred_at\": \"2024-01-19T19:29:34.576Z\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"name\": \"add_signer\",\r\n"
				+ "        \"data\": {\r\n"
				+ "          \"user\": {\r\n"
				+ "            \"email\": \"suporte@ectare.com.br\",\r\n"
				+ "            \"name\": \"Samuel Vilas Boas Coimbra\"\r\n"
				+ "          },\r\n"
				+ "          \"account\": { \"key\": \"7517be57-04e6-4c33-a65f-218311ebb50b\" },\r\n"
				+ "          \"signers\": [\r\n"
				+ "            {\r\n"
				+ "              \"sign_as\": \"witness\",\r\n"
				+ "              \"key\": \"23aa5776-8b4a-410c-95d0-f894b60b4bb3\",\r\n"
				+ "              \"email\": \"ana.arantes@ectare.com.br\",\r\n"
				+ "              \"name\": \"Ana Marta Arantes Caetano\",\r\n"
				+ "              \"birthday\": null,\r\n"
				+ "              \"documentation\": null,\r\n"
				+ "              \"has_documentation\": false,\r\n"
				+ "              \"created_at\": \"2024-01-19T16:29:33.587-03:00\",\r\n"
				+ "              \"auths\": [\"email\"],\r\n"
				+ "              \"selfie_enabled\": false,\r\n"
				+ "              \"handwritten_enabled\": false,\r\n"
				+ "              \"official_document_enabled\": false,\r\n"
				+ "              \"liveness_enabled\": false,\r\n"
				+ "              \"facial_biometrics_enabled\": false,\r\n"
				+ "              \"communicate_by\": \"email\",\r\n"
				+ "              \"list_key\": \"42b72bf4-1150-4f61-9346-a6e6ea446da1\",\r\n"
				+ "              \"url\": \"https://app.clicksign.com/sign/23aa5776-8b4a-410c-95d0-f894b60b4bb3\",\r\n"
				+ "              \"read_receipts?\": false\r\n"
				+ "            }\r\n"
				+ "          ]\r\n"
				+ "        },\r\n"
				+ "        \"occurred_at\": \"2024-01-19T19:29:33.857Z\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"name\": \"add_signer\",\r\n"
				+ "        \"data\": {\r\n"
				+ "          \"user\": {\r\n"
				+ "            \"email\": \"suporte@ectare.com.br\",\r\n"
				+ "            \"name\": \"Samuel Vilas Boas Coimbra\"\r\n"
				+ "          },\r\n"
				+ "          \"account\": { \"key\": \"7517be57-04e6-4c33-a65f-218311ebb50b\" },\r\n"
				+ "          \"signers\": [\r\n"
				+ "            {\r\n"
				+ "              \"sign_as\": \"sign\",\r\n"
				+ "              \"key\": \"ccfd5350-a7a3-43e7-bb01-de72590ccef0\",\r\n"
				+ "              \"email\": \"ely@agely.com.br\",\r\n"
				+ "              \"name\": \"Jose Testador\",\r\n"
				+ "              \"birthday\": null,\r\n"
				+ "              \"documentation\": null,\r\n"
				+ "              \"has_documentation\": false,\r\n"
				+ "              \"created_at\": \"2024-01-19T16:29:33.019-03:00\",\r\n"
				+ "              \"auths\": [\"whatsapp\"],\r\n"
				+ "              \"selfie_enabled\": true,\r\n"
				+ "              \"handwritten_enabled\": false,\r\n"
				+ "              \"official_document_enabled\": false,\r\n"
				+ "              \"liveness_enabled\": false,\r\n"
				+ "              \"facial_biometrics_enabled\": false,\r\n"
				+ "              \"communicate_by\": \"email\",\r\n"
				+ "              \"phone_number\": \"35988340372\",\r\n"
				+ "              \"phone_number_hash\": \"48827ec0561b87e41be2f88673e68a6a086291547832db90520e4446601a634c\",\r\n"
				+ "              \"list_key\": \"61f867f2-6cfd-42af-b62d-7ec45c3b9805\",\r\n"
				+ "              \"url\": \"https://app.clicksign.com/sign/ccfd5350-a7a3-43e7-bb01-de72590ccef0\",\r\n"
				+ "              \"read_receipts?\": false\r\n"
				+ "            }\r\n"
				+ "          ]\r\n"
				+ "        },\r\n"
				+ "        \"occurred_at\": \"2024-01-19T19:29:33.307Z\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"name\": \"update_deadline\",\r\n"
				+ "        \"data\": {\r\n"
				+ "          \"user\": {\r\n"
				+ "            \"email\": \"suporte@ectare.com.br\",\r\n"
				+ "            \"name\": \"Samuel Vilas Boas Coimbra\"\r\n"
				+ "          },\r\n"
				+ "          \"account\": { \"key\": \"7517be57-04e6-4c33-a65f-218311ebb50b\" },\r\n"
				+ "          \"deadline_at\": \"2024-02-08T23:59:59.000-03:00\"\r\n"
				+ "        },\r\n"
				+ "        \"occurred_at\": \"2024-01-19T19:29:32.739Z\"\r\n"
				+ "      },\r\n"
				+ "      {\r\n"
				+ "        \"name\": \"upload\",\r\n"
				+ "        \"data\": {\r\n"
				+ "          \"user\": {\r\n"
				+ "            \"email\": \"suporte@ectare.com.br\",\r\n"
				+ "            \"name\": \"Samuel Vilas Boas Coimbra\"\r\n"
				+ "          },\r\n"
				+ "          \"account\": { \"key\": \"7517be57-04e6-4c33-a65f-218311ebb50b\" },\r\n"
				+ "          \"deadline_at\": \"2024-02-18T16:29:32.032-03:00\",\r\n"
				+ "          \"auto_close\": true,\r\n"
				+ "          \"locale\": \"pt-BR\"\r\n"
				+ "        },\r\n"
				+ "        \"occurred_at\": \"2024-01-19T19:29:32.285Z\"\r\n"
				+ "      }\r\n"
				+ "    ],\r\n"
				+ "    \"attachments\": [],\r\n"
				+ "    \"links\": {\r\n"
				+ "      \"self\": \"/accounts/35498/folders/24495056/documents/1c215ef6-f92f-4f81-8477-25cdd726b33e\"\r\n"
				+ "    }\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "";
		
		System.out.println(tratamentoSqlInjectEmString(json));
		
	}
}
